### ISSUE TITLE
Add variables to dashboard

### ISSUE THREAD

**Issue by rochecompaan** [upfrontsystems/izinto-angular#13]
A user should be able to add simple variables to a dashboard that will allow them to re-use the values in a query. A good example would be the device id. If a user can add a variable named `dev_id` to the dashboard, they can reuse that value in a query with the colon syntax, eg: `:dev_id:`.

The UI can look like this:
```
+-------------------------------------------------------+
|                                                       |
|  Title:   [                   ]                       |
|                                                       |
|  Description:                                         |
|                                                       |
|  +--------------------------------------------------+ |
|  |                                                  | |
|  |                                                  | |
|  +--------------------------------------------------+ |
|                                                       |
|  Variables:                                           |
|                                                       |
|  id      | value                                      |
|  ------------------------------                       |
|  dev_id  | station_001          [ edit ] [ delete ]   |
|                                                       |
|  [ add ]                                              |
|                                                       |
+-------------------------------------------------------+
```

**Comment by GronumSmith** [comment]
Adding here: Although this is now applicable to how dashboards will be done in future (also charts ?)
Fundamentally is this what we are aiming for?

Variables: is the Where/Which Site/Installation/Device?
Queries: is the What parameters I want to see
Edit: How is this being displayed 
This will allow such templates to be copy edit easily and "fast" scaling

![image](https://user-images.githubusercontent.com/35992133/94454303-fec38e00-01b1-11eb-92a2-758cd3f4f890.png)

**Comment by GronumSmith** [comment]
Variables worked in Charts, I am not sure how they are being used with scripts, as explained above.
When we have a template we would like to be able to copy / paste this for other sites/installations.  The best place to change the Site_ID/Installation_ID is in "Variables"  so that the queries will go and lookup the variables.

**Comment by nvernooy** [comment]
Variables are formatted into queries similar how it is done in charts

Also now variables are available in scripts with a dictionary keyed on the variable name

The variable
![image](https://user-images.githubusercontent.com/5332516/100616164-5fda2000-3321-11eb-955d-bf7c25169241.png)

can be referenced by
`siteId = variables['site_id'].value`

**Comment by GronumSmith** [comment]
Thanks Niel, I just want to check/test
Here: https://dashtweak.com/dashboards/315/view 
1) I am for now using the var as "dev_id_var" = 1406300003 in the Var field. I would like to use this in the "old" SingleStat Query and in the Chart.  
Is this supposed to work? 
![image](https://user-images.githubusercontent.com/35992133/100874916-f3405c00-34ad-11eb-88f8-a532f7c2e3cc.png)

2) I will appreciate it if you can show how your implementation will work for this Table
https://dashtweak.com/dashboards/316/view 
or else a simple example template 
Thanks

**Comment by nvernooy** [comment]
@GronumSmith for charts and single stats we originally used a colon, `:dev_id:`, format for variables, however in scripts we use a javascript format, `${dev_id}`, for all purposes.

In die examples you've linked I have added variables and updated the query to use it, so in the single stat the query changed to `SELECT last("humidity") FROM "izintorain"."autogen"."measurement" WHERE "dev_id" =':dev_id_var:' AND time>now()-1h`.
It's a bit confusing, but since we plan to eventually replace all charts with scripts, then queries will use the same format.

**Comment by GronumSmith** [comment]
Thanks Niel
Will have a look asap, and understand the temporary confusion.
