### ISSUE TITLE
GIS Map: Pin the popup in a nice way to the "tag" / pin

### ISSUE THREAD

**Issue by GronumSmith** [upfrontsystems/izinto-angular#192]
At the moment the popup:
a) covers the pin / tag
b) the arrow of the call-out is not anchored to any specific point

Suggestions 
1) Call-out/pop-out is anchored above the pin/tag ?   [easier but then duplicate data?]
2) the pin/tag is hidden completely by the new popup, and the popup arrow is on the same point as the arrow of the pin/tag [make border of popup same as pin/tag to make it appear to expand
any of these two methods 
![image](https://user-images.githubusercontent.com/35992133/94457062-5ebb3400-01b4-11eb-9539-8be492b6f321.png)

**Comment by nvernooy** [comment]
Change the layout of the pins and the position of the popup

![image](https://user-images.githubusercontent.com/5332516/94573532-7bb63c80-0272-11eb-9dae-66ec67e87a01.png)
![image](https://user-images.githubusercontent.com/5332516/94573730-a7392700-0272-11eb-842b-75dac8d2d1c2.png)

**Comment by rochecompaan** [comment]
@GronumSmith are you happy with the popup position? Can we close this issue?

**Comment by GronumSmith** [comment]
Sorry closed this too early.   I miss a pin -> sharp end to the EXACT GPS location, similar to (an the same location/point) as the popup. 
![image](https://user-images.githubusercontent.com/35992133/94674410-68f64300-0318-11eb-9af6-4e00994d56d3.png)

in other words maybe have an arrow/point above the [] to the same point as the arrow of the Pop-up. 
![image](https://user-images.githubusercontent.com/35992133/94674534-9e029580-0318-11eb-8712-ab8b22e79699.png)

This will imply a little bit of space between the pin[] and the pop-up.  Would that be OK

**Comment by GronumSmith** [comment]
BTW: Tested in : https://dashtweak.com/dashboards/162

**Comment by rochecompaan** [comment]
Making a pointy marker is not as easy as styling a rectangle or circle with HTML and CSS. Is it important to for the marker to point exactly to the GPS coordinate? In the example you liked it doesn't do that:

![image](https://user-images.githubusercontent.com/784273/94675117-84158280-0319-11eb-9768-35336fea55af.png)

In the original example it doesn't either:

![image](https://user-images.githubusercontent.com/784273/94675249-b7f0a800-0319-11eb-9409-30f5363d4792.png)

We could remove the icons for temp, wind-speed, etc and always show a dot to render on the GPS location.

If you have an existing leaflet marker example then we can cut and paste this is doable otherwise I think we should do this as a future enhancement.

**Comment by rochecompaan** [comment]
@nvernooy can we position the centre point of the pin on the exact GPS coordinate.

**Comment by nvernooy** [comment]
The center of the pin is on the GPS coordinate

![image](https://user-images.githubusercontent.com/5332516/94905639-7d177d00-049d-11eb-8e58-d826e2566d1f.png)
